### ISSUE TITLE
Issue with getting data twice.

### ISSUE THREAD

**Issue by dtracers** [miki725/alchemy-mock#13]
I have this code early on in the setup where it basically checks that a certain piece of data exists:

```
 group_name_query = _session.query(Group).filter(Group.name == group_name)
            if not _session.query(group_name_query.exists()).scalar():
                group = Group(name=group_name)
                _session.add(group)
```

And this works just fine but later on I go over it again this time retrieving the values:

```
for group_name in groups_to_add:
            value = _session.query(Group).filter(Group.name == group_name).first()
            i = value.id
            ids[group_name] = i
            ids_to_group[i] = group_name
```

No matter what I do this second time the mocked result will always be empty
Is there a way to add something so that it is returned on a second match?
I know in your example docs it does not return again and is empty.

**Comment by iamliamc** [comment]
I'm also trying to figure out if this library is viable for my needs: 

Can anyone with more experience chime in? As far as I can tell it doesn't look like 

> session.add()

 is a viable call. 

These appear to be the only available methods on a UnifiedAlchemyMagicMock object:
`['__iter__', '__name__', 'add_columns', 'all', 'assert_any_call', 'assert_called', 'assert_called_once', 'assert_called_once_with', 'assert_called_with', 'assert_has_calls', 'assert_not_called', 'attach_mock', 'boundary', 'call_args', 'call_args_list', 'call_count', 'called', 'configure_mock', 'count', 'filter', 'filter_by', 'first', 'get', 'group_by', 'join', 'limit', 'method_calls', 'mock_add_spec', 'mock_calls', 'one', 'options', 'order_by', 'query', 'reset_mock', 'return_value', 'side_effect', 'unify']`

To seed data for a test it looks like this: 
`            session = UnifiedAlchemyMagicMock(data=[
                (
                    [mock.call.query(Series)],
                    [Series(uuid="123123123"), Series(uuid="234234234")]
                )
            ])`

The thing I don't know how to test is querying this object, updating it, and then testing that it was updated properly... any help?

**Comment by miki725** [comment]
just added basic `.add()` support in https://github.com/miki725/alchemy-mock/pull/16. you can see sample usage in https://github.com/miki725/alchemy-mock/pull/16/files#diff-b09937195996ddc2fe43c8a2b3b836d0R249. not full support yet but at least some initial support

**Comment by dtracers** [comment]
That would be a really great solution to solve this as well!
Thanks!

**Comment by miki725** [comment]
just released new version. let me know if that works ok

**Comment by miki725** [comment]
I presume the release works. feel free to reopen issue if you find any issues. thanks

**Comment by iamliamc** [comment]
I'll check it out, thanks for your efforts!
