### ISSUE TITLE
Can I mock session.add() ?

### ISSUE THREAD

**Issue by mcauto** [miki725/alchemy-mock#15]
Hello! I love this library!

I want to mock session.add()...

```python
[
    mock.call.add(Model_instance),
    mock.call.commit()
]
```
help me plz..

**Comment by miki725** [comment]
`session.add()` was not treated in any special way by the library. it stayed as a standard mocked function.

adding initial `.add()` support in https://github.com/miki725/alchemy-mock/pull/16. you can see usage example in https://github.com/miki725/alchemy-mock/pull/16/files#diff-b09937195996ddc2fe43c8a2b3b836d0R249

**Comment by miki725** [comment]
just released new version with basic `.add()` support. this seems more of a question ticker rather than a bug report but feel free to reopen or create another issue if you have questions/issues/suggestions

**Comment by mcauto** [comment]
Thank you! It's works!
