### ISSUE TITLE
Need support for "distinct" function

### ISSUE THREAD

**Issue by sirawats** [miki725/alchemy-mock#26]
This is my example query and using UnifiedAlchemyMagicMock for my test

db.query(ModelA).distinct(ModelA.attr_1).group_by(ModelA.attr_2, ModelA.attr_1).filter(ModelA.attr_2 == 10).all()

I can not use distinct in my query

**Comment by miki725** [comment]
`distinct` is currently not supported

https://github.com/miki725/alchemy-mock/blob/0ab8f147c87ac6aa35b628b6460c92d2e1048de4/alchemy_mock/mocking.py#L313-L323

pr is welcome adding support 😄
