### ISSUE TITLE
Failing in Python 3.6.8

### ISSUE THREAD

**Issue by fpozzobon** [miki725/alchemy-mock#8]
Hi,

I am getting the following error when trying to execute in 3.6.8 : 
```    
 def __eq__(self, other):
        _other = list(other)
        _other[-2] = UnorderedTuple(other[-2])
>       other = Call(tuple(_other), **vars(other))
E       TypeError: __new__() got an unexpected keyword argument '_mock_name'

../../.local/share/virtualenvs/jobsite-api-sGWrxjA3/lib/python3.6/site-packages/alchemy_mock/mocking.py:57: TypeError 
```

**Comment by miki725** [comment]
What are you trying to do overall?

**Comment by fpozzobon** [comment]
Hi, we are mocking alchemy query using 
``` UnifiedAlchemyMagicMock(data=[(
[mock.call.query(MyDTO)]
)]) ```

**Comment by miki725** [comment]
the data is meant to pass model instances. for example:

```python
UnifiedAlchemyMagicMock(data=[(
  [mock.call.query(MyDTO)],
  [MyDTO(...)]
)]) 
```

**Comment by fpozzobon** [comment]
True :)
Unfortunately I am getting this error on version 3.6.8... tried 3.7.3 same issue.
Version 3.6.5 works like a charm though...
Sounds like the mock library slightly changed in later version :/

**Comment by mariuszh** [comment]
Hi,

Do you have any information about this bug? How to fix it? Maybe you have same workaround? Unfortunately because of this bug library is unusable in python version 3.6.8.

**Comment by dtracers** [comment]
That did not solve it for me.
I am having issue in python 3.7 with this
note that I am returning a db object.


self = call.filter(BinaryExpression(sql='groups.name = :name_1', params={'name_1': 'admin'}), BinaryExpression(sql='groups.na...name = :name_1', params={'name_1': 'beta'}), BinaryExpression(sql='groups.name = :name_1', params={'name_1': 'admin'}))
other = call.query(<class 'backend.database.objects.Group'>)

```
    def __eq__(self, other):
        _other = list(other)
        _other[-2] = UnorderedTuple(other[-2])
>       other = Call(tuple(_other), **vars(other))
E       TypeError: __new__() got an unexpected keyword argument '_mock_name'

..\..\..\..\carball\venv\lib\site-packages\alchemy_mock\mocking.py:57: TypeError
```

**Comment by dtracers** [comment]
```
_other = list(other)
_other[-2] = UnorderedTuple(other[-2])
other = Call(tuple(_other), **vars(other))
```

They changed the constructor to take in the variables but without the `_mock_`

**Comment by dtracers** [comment]
You have to do
`pip install mock==2.0.0 `

Any newer version will crash or cause infinite recursion.
Would be nice if this could be fixed to work on newer versions

**Comment by mariuszh** [comment]
Yes, only version 2.0.0 solve this problem.

**Comment by miki725** [comment]
sorry for the delay. can anyone give this branch a try `latest-mock` https://github.com/miki725/alchemy-mock/pull/10. should fix the issue. if all is good Ill release a new version to pypi

**Comment by miki725** [comment]
new version pushed to pypi - 0.3.5
